# Run in default virtualenv, but with access to Python packages
# installed by apt
language: python
virtualenv:
  system_site_packages: true
addons:
  apt:
    sources:
    - sourceline: 'ppa:openshot.developers/libopenshot-daily'
    packages:
    - libopenshot-audio-dev
    - libopenshot-dev
    - libssl-dev
    - python3-openshot
    - python3
    - python3-pip
    - python3-setuptools
    - python3-pyqt5
    - python3-pyqt5.qtmultimedia
    - python3-pyqt5.qtopengl
    - python3-pyqt5.qtsvg
    - python3-pyqt5.qtwebkit
    - python3-requests
    - python3-xdg
    - python3-zmq
    - qttranslations5-l10n
    - xvfb

matrix:
  include:
    - name: "Ubuntu 16.04 Xenial"
      os: linux
      dist: xenial
    - name: "Ubuntu 18.04 Bionic"
      os: linux
      dist: bionic

#before_install:
#  - wget https://files.pythonhosted.org/packages/d0/6d/9492644452727094543575de9846af5a2b9c764f760e2d414af7c876618c/cx_Freeze-5.0.1.tar.gz
#  - tar xf cx_Freeze-5.0.1.tar.gz
#  - cd cx_Freeze-5.0.1; python3 setup.py build; python3 setup.py install --user; cd ..;
#  - pwd

install:
  - pip3 install cx-freeze

script:
  - python3 freeze.py build
  - xvfb-run --auto-servernum --server-num=1 --server-args "-screen 0 1920x1080x24" python3 src/tests/query_tests.py

notifications:
  email: true

env:
  global:
  - TRAVIS_LIBOPENSHOT=TEST
  - LANG="en_US.UTF-8"
